version: '3.8'

services:
  web:
    build: .
    restart: always
    volumes:
      - static-data:/assets/static
    secrets:
      - db_schema_name
      - db_user_name
      - db_user_password
      - aws_access_key
      - aws_secret_key
      - aws_bucket_name
      - sendgrid_api_key
    environment:
      DEBUG: 0
      MYSQL_HOST: db
      MYSQL_DATABASE: /run/secrets/db_schema_name
      MYSQL_USER: /run/secrets/db_user_name
      MYSQL_PASSWORD: /run/secrets/db_user_password
      AWS_ACCESS_KEY: /run/secrets/aws_access_key
      AWS_SECRET_KEY: /run/secrets/aws_secret_key
      AWS_BUCKET_NAME: /run/secrets/aws_bucket_name
      SENDGRID_API_KEY: /run/secrets/sendgrid_api_key
    depends_on:
      - db

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    volumes:
      - static-data:/static
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf/:/etc/letsencrypt/:rw
      - ./certbot/www/:/var/www/certbot/:rw

  db:
    image: mysql:8.0
    restart: always
    secrets:
      - db_root_password
      - db_schema_name
      - db_user_name
      - db_user_password
    volumes:
      - asset-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_DATABASE_FILE=/run/secrets/db_schema_name
      - MYSQL_USER_FILE=/run/secrets/db_user_name
      - MYSQL_PASSWORD_FILE=/run/secrets/db_user_password
    ports:
      - 3306:3306

volumes:
  static-data:
  asset-db-data:

secrets:
  db_root_password:
    file: ./secrets/db/root_password.txt
  db_schema_name:
    file: ./secrets/db/schema_name.txt
  db_user_name:
    file: ./secrets/db/user_name.txt
  db_user_password:
    file: ./secrets/db/user_password.txt
  aws_access_key:
    file: ./secrets/aws/aws_access_key.txt
  aws_bucket_name:
    file: ./secrets/aws/aws_bucket_name.txt
  aws_secret_key:
    file: ./secrets/aws/aws_secret_key.txt
  sendgrid_api_key:
    file: ./secrets/sendgrid/api_key.txt
