# Generated by Django 4.1.3 on 2023-12-21 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='expense',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
