# Generated by Django 4.1.3 on 2023-12-22 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets_management', '0003_remove_tenant_contact_tenant_email_tenant_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='asset',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='assets_management.asset'),
            preserve_default=False,
        ),
    ]
