# Generated by Django 4.1.3 on 2023-12-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_management', '0004_tenant_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
