# Generated by Django 4.1.3 on 2023-12-26 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets_management', '0005_tenant_is_current_alter_tenant_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='assets_management.asset'),
        ),
    ]
