# Generated by Django 4.1.3 on 2023-12-26 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets_management', '0006_alter_tenant_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='asset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='assets_management.asset'),
            preserve_default=False,
        ),
    ]
