# Generated by Django 4.1.3 on 2023-12-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_management', '0007_archive_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='file_type',
            field=models.CharField(choices=[('image', 'image'), ('video', 'video')], default=1, max_length=5),
            preserve_default=False,
        ),
    ]
