# Generated by Django 5.0 on 2023-12-27 08:52

import assets_management.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_management', '0008_archive_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='file',
            field=models.FileField(upload_to='archive', validators=[assets_management.validators.validate_format]),
        ),
        migrations.AlterField(
            model_name='archive',
            name='file_type',
            field=models.CharField(blank=True, choices=[('image', 'image'), ('video', 'video')], max_length=5),
        ),
        migrations.AlterField(
            model_name='asset',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='asset'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='contract'),
        ),
    ]
