# Generated by Django 5.0 on 2023-12-27 18:45

import assets_management.models
import assets_management.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_management', '0009_alter_archive_file_alter_archive_file_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=9)),
                ('document', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='archive',
            name='file',
            field=models.FileField(upload_to=assets_management.models.archive_directory_path, validators=[assets_management.validators.validate_format]),
        ),
        migrations.AlterField(
            model_name='asset',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=assets_management.models.asset_directory_path),
        ),
    ]
