# Generated by Django 5.0 on 2023-12-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_management', '0010_generalexpense_alter_archive_file_alter_asset_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generalexpense',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='archive',
            name='file_type',
            field=models.CharField(blank=True, choices=[('video', 'video'), ('image', 'image')], max_length=5),
        ),
    ]
