# Generated by Django 5.0 on 2023-12-29 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_management', '0011_expense_description_generalexpense_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets_management.address'),
        ),
    ]
