# Generated by Django 5.0 on 2024-02-14 15:19

import assets_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_management', '0012_alter_asset_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=assets_management.models.asset_income_directory_path),
        ),
        migrations.AlterField(
            model_name='contract',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=assets_management.models.contract_directory_path),
        ),
        migrations.AlterField(
            model_name='expense',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=assets_management.models.asset_expense_directory_path),
        ),
        migrations.AlterField(
            model_name='generalexpense',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=assets_management.models.general_expense_directory_path),
        ),
    ]
