# Generated by Django 5.0 on 2024-02-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_management', '0013_income_document_alter_contract_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
