# Generated by Django 5.0 on 2024-03-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_management', '0016_expense_tax_deductible_alter_archive_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='registration_number',
            field=models.CharField(default='777.777.777-77', max_length=20),
        ),
    ]
