# Generated by Django 5.0 on 2024-03-17 10:30

import assets_management.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_management', '0017_tenant_is_company_tenant_registration_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deed',
            fields=[
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='deed', serialize=False, to='assets_management.asset')),
                ('file', models.FileField(blank=True, null=True, upload_to=assets_management.models.deed_directory_path)),
            ],
        ),
    ]
