# Generated by Django 5.0 on 2024-04-10 22:12

import assets_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_management', '0019_alter_archive_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('file', models.FileField(blank=True, null=True, upload_to=assets_management.models.report_directory_path)),
            ],
        ),
        migrations.AlterField(
            model_name='archive',
            name='file_type',
            field=models.CharField(blank=True, choices=[('video', 'video'), ('image', 'image')], max_length=5),
        ),
    ]
