# Generated by Django 5.0 on 2024-04-13 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_management', '0020_report_alter_archive_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerUnity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('energia & gás', 'energia & gás'), ('água', 'água'), ('gás', 'gás'), ('energia', 'energia')], max_length=16)),
                ('number', models.CharField(max_length=255)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets_management.asset')),
            ],
        ),
    ]
