# Generated by Django 5.0 on 2024-04-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_management', '0021_consumerunity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerunity',
            name='source',
            field=models.CharField(choices=[('E', 'energia'), ('G', 'gás'), ('W', 'água')], max_length=16),
        ),
    ]
