# Generated by Django 5.0 on 2024-04-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_management', '0022_alter_consumerunity_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerunity',
            name='source',
            field=models.CharField(choices=[('W', 'água'), ('G', 'gás'), ('E', 'energia')], max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name='consumerunity',
            unique_together={('asset', 'source')},
        ),
    ]
