# Generated by Django 5.0 on 2024-08-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_management', '0024_alter_consumerunity_asset_alter_consumerunity_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='post',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
