# Generated by Django 5.0 on 2024-08-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_management', '0025_archive_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='file_type',
            field=models.CharField(blank=True, choices=[('image', 'image'), ('video', 'video')], max_length=5),
        ),
    ]
