# Generated by Django 5.0 on 2024-08-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_management', '0026_alter_archive_file_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archive',
            old_name='post',
            new_name='poster',
        ),
        migrations.AlterField(
            model_name='archive',
            name='file_type',
            field=models.CharField(blank=True, choices=[('video', 'video'), ('image', 'image')], max_length=5),
        ),
        migrations.AlterField(
            model_name='consumerunity',
            name='source',
            field=models.CharField(choices=[('W', 'água'), ('G', 'gás'), ('E', 'energia')], max_length=16),
        ),
    ]
